# This is a basic workflow to help you get started with Actions

name: PHPStan

# Controls when the action will run. 
on: push
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  phpstan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Startup
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Create Vendor Directory
        run: |
          echo Making directory...
          mkdir vendor
          echo Directory made.
      # Checkout iTheTrollIdk/libBungeeCore
      - name: Checkout libBungeeCore
        uses: actions/checkout@v2
        with:
        repository: iTheTrollIdk/libBungeeCore
        token: ${{ secrets.TOKEN }}
        submodules: true
        path: vendor/libBungeeCore
        ref: master
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Run PHPStan
        uses: nxtlvlsoftware/pmmp-phpstan-action@4
        with:
          phpstan-config: phpstan.neon.dist